version: '3'
services:
  db:
    image: postgres:9.4.5
    environment:
      POSTGRES_USER: ruby-app
      POSTGRES_PASSWORD: ruby-app-development
    ports:
      - '5432:5432'
  web:
    build: .
    command: ruby main.rb
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: ruby-app
      POSTGRES_PASSWORD: ruby-app-development
      APP_ENV: development
    ports:
      - "4567:4567"
    depends_on:
      - db
