version: 2
jobs:
  lint:
    services:
      - docker
    working_directory: "~/ruby-app"
    docker:
      - image: circleci/ruby:2.6.3-stretch
    environment:
      RAILS_ENV: test
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Installing dependencies (Linux)
          command: |
            sudo apt-get update -qq
            sudo apt-get install -y build-essential libpq-dev nodejs
      - run:
          name: Installing dependencies (bundler)
          command: |
            bundle install
      - run:
          name: Executing rubocop
          command: bundle exec rubocop -R

  build:
    services:
      - docker
    working_directory: "~/ruby-app"
    docker:
        - image: circleci/ruby:2.6.3-stretch
    environment:
      RAILS_ENV: test
      PORT: 4567
      POSTGRES_HOST: db
      POSTGRES_USER: ruby-app
      POSTGRES_PASSWORD: ruby-app-development
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Installing dependencies (Linux)
          command: |
            sudo apt-get update -qq 
            sudo apt-get install -y build-essential libpq-dev nodejs
      - run:
          name: Installing dependencies (Ruby)
          command: bundle install
      - run:
          name: Starting Container with Database
          command: |
            docker run --name postgres \
            -e POSTGRES_USER=${POSTGRES_USER} \
            -e POSTGRES_PASSWORD=${POSTGRES_PASSWORD} \
            -p 5432:5432 \
            -d postgres:9.4.5
            sleep 10
      - run:
          name: Executing rake tasks
          command: rake db:drop db:create db:migrate db:seed
      - run:
          name: Execute tests
          command: rspec

workflows:
 version: 2
 build_commits:
   jobs:
     - lint
     - build
