version: 2
jobs:
  lint:
    services:
      - docker
    working_directory: "~/ruby-app"
    docker:
        - image: circleci/ruby:2.6.3-stretch
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Installing dependencies (Linux)
          command: apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs
      - run:
          name: Installing dependencies (bundler)
          command: |
            bundle install
      - run:
          name: Executing rubocop
          command: bundle exec rubocop -R

  build:
    services:
      - docker
    working_directory: "~/ruby-app"
    docker:
        - image: circleci/ruby:2.6.3-stretch
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build docker-container
          command: docker-compose build
      - run:
          name: Executing rake tasks
          command: |
            docker-compose run --rm web rake db:drop db:create db:migrate db:seed
      - run:
          name: Execute tests
          command: docker-compose run --rm web rspec

workflows:
 version: 2
 build_commits:
   jobs:
     - lint
     - build
