version: 2
jobs:
  lint:
    services:
      - docker
    working_directory: "~/ruby-app"
    docker:
      - image: circleci/ruby:2.6.3-stretch
    environment:
      RAILS_ENV: test
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Installing dependencies (Linux)
          command: |
            sudo apt-get update -qq
            sudo apt-get install -y build-essential libpq-dev nodejs
      - run:
          name: Installing dependencies (bundler)
          command: |
            bundle install
      - run:
          name: Executing rubocop
          command: bundle exec rubocop -R

  build:
    services:
      - docker
    working_directory: "~/ruby-app"
    docker:
        - image: circleci/ruby:2.6.3-stretch
    environment:
      RAILS_ENV: test
      PORT: 4567
      POSTGRES_HOST: 127.0.0.1
      POSTGRES_USER: ruby-app
      POSTGRES_PASSWORD: ruby-app-development
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Bulding container
          command: docker build -f docker/Dockerfile -t rubyapp --no-cache .
      - run:
          name: Wait Database to initialize and execute rake tasks
          command: |
            docker-compose run --service-ports api \
            bundle install && ./init/wait_db.sh && \
            rake db:drop db:create db:migrate db:seed
      - run:
          name: Execute tests
          command: docker-compose run --service-ports api rspec

workflows:
 version: 2
 build_commits:
   jobs:
     - lint
     - build
