version: '3'
services:
  proxy:
    container_name: proxy
    image: dockercloud/haproxy
    depends_on:
      - api
    environment:
      - BALANCE=leastconn
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
    networks:
      - web
    deploy:
      placement:
        constraints: [node.role == manager]
  db:
    image: postgres:9.4.5
    environment:
      POSTGRES_USER: ruby-app
      POSTGRES_PASSWORD: ruby-app-development
    ports:
      - '5432:5432'
    networks:
      - web

  api:
    image: rubyapp:latest
    deploy:
      replicas: 3
    environment:
      PORT: 4567
      PUMA_WORKERS: 2
      PUMA_MAX_THREADS: 5
      POSTGRES_HOST: db
      POSTGRES_USER: ruby-app
      POSTGRES_PASSWORD: ruby-app-development
      RAILS_ENV: production
    ports:
      - "4567:4567"
    depends_on:
      - db
    networks:
      - web

networks:
  web:
    driver: overlay
