default: &default
  adapter: postgresql
  encoding: unicode
  user: postgres
  password: postgres
  pool: 5
  host: db

development:
  <<: *default
  database: ruby_app_dev

test:
  <<: *default
  database: ruby_app_test

production:
  <<: *default
  database: ruby_app
