default: &default
  adapter: postgresql
  encoding: unicode
  user: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "127.0.0.1" }%>

development:
  <<: *default
  database: ruby_app_dev

test:
  <<: *default
  database: ruby_app_test

production:
  <<: *default
  database: ruby_app
